### ISSUE TITLE
Bot is not posting data

### ISSUE THREAD

**Issue by Dakihub** [Lokraan/Hasami#12]
Hey!

Finally got the bot up and running on my server.

However, when I type !start (changed $ to ! to avoid bot conflicts) the bot doesn't collect or post any data.

I'm sure its probably user error. Am I doing something wrong? I haven't changed any of the code besides the prefix..

Thanks!!

**Comment by Lokraan** [comment]
I changed the configuration for myself and was able to see it working. It should tell you it's starting in Discord if it registered the command.

I added a command prefix option in config.json, and if you use that it automatically changes the command prefix for all the commands.

Let me know what happens, thanks 🔢

**Comment by Dakihub** [comment]
Hey thanks so much for your fast response!

[image: Inline image 1]

The bot launches but once it starts nothing really happens..
I'm not sure whats happening...

**Comment by Dakihub** [comment]
Oops the picture didnt send...

https://gyazo.com/7b8e8a2ee2388fee52b28335ff634f93

**Comment by Lokraan** [comment]
This is an issue with your router not my code.

There's two solutions to this though.
1) Follow the solutions given [here](https://github.com/ccxt/ccxt/issues/452)
2) Replace check_markets with: 
```python
	async def check_markets(self) -> None:
		"""
		Processes bittrex and binance markets for signifcant price/rsi updates 
		and sends outputs to discord.
		
		Does while self._updating is true every interval minutes. 
		Args:
			None
		Returns:
			None
		
		"""
		async with aiohttp.ClientSession() as session:

			# load markets
			await self._load_markets(session)

			# loop through at least once
			while self._updating:
				price_updates = {}

				self._logger.info("Checking markets")

				outputs, price_updates["Bittrex"] = await self._check_bittrex_markets(
					session
					)

				self._logger.debug("Outputs: {0}".format(outputs))

				self._update_prices(price_updates)

				embed = self._create_embed(outputs)
				await self._client.send_message(
					destination=discord.Object(id=self._update_channel), embed=embed
					)

				self._logger.debug("Async sleeping {0}".format(str(self._interval * 60)))
				
				await asyncio.sleep(int(self._interval*60))
```
The downside to this though is that you will no longer be watching Binance's markets for price fluctuations.

**Comment by Dakihub** [comment]
Oh bummer :(

My team mostly only uses Binance. Is there something I can do to my router??

Thanks for all your help by the way!

**Comment by Lokraan** [comment]
I personally have no idea, sorry.

**Comment by Dakihub** [comment]
It's all good I'll keep looking into it. Thanks so much for your help!!
